apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runner.fullname" . }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: SECRET_GITHUB_API_URL
              value: {{ .Values.runner.api_url }}
            - name: SECRET_GITHUB_ORG
              value: {{ .Values.runner.organisation }}
            - name: SECRET_GITHUB_URL
              value: {{ .Values.runner.url }}
            - name: SECRET_NAME
              value: {{ .Values.runner.name }}
            - name: SECRET_GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ include "runner.fullname" . }}-github"
                  key: app_id
            - name: SECRET_KEY_PATH
              value: "/github_app_key/app.pem"
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- with .Values.capabilities }}
            capabilities:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          volumeMounts:
            - mountPath: "/github_app_key"
              name: appkey
              readOnly: true
      {{- if .Values.image.auth.enabled }}
      imagePullSecrets:
        - name: {{ .Values.image.auth.secret_name | default (printf "%s" ( include "runner.fullname" . )) }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: appkey
          secret:
            items:
              - key: rsa_key
                path: app.pem
            secretName: "{{ include "runner.fullname" . }}-github"
