apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "runner.fullname" . }}-github"
stringData:
  app_id: {{ quote .Values.runner.app_id }}
  rsa_key: {{ toYaml .Values.runner.rsa_key | indent 2}}
type: Opaque
