{{- if and .Values.image.auth.enabled .Values.image.auth.password .Values.image.auth.username .Values.image.auth.email }}
apiVersion: v1
data:
  .dockerconfigjson: {{ include "imagePullSecret" . | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.image.auth.name | default (printf "%s" ( include "runner.fullname" . )) }}
type: kubernetes.io/dockerconfigjson
{{- end }}
