apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bandersnatch.fullname" . }}
  labels:
    {{- include "bandersnatch.labels" . | nindent 4 }}
    component: bandersnatch
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bandersnatch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bandersnatch.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.bandersnatch.repository }}:{{ .Values.image.bandersnatch.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.bandersnatch.pullPolicy }}
          command:
            - "python"
          args:
            - "/bandersnatch/src/runner.py"
            - "--force-check"
            - "true"
            - "{{- .Values.update_interval }}" # hourly
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /conf
            - name: data
              mountPath: /srv/pypi/web
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim | default (include "bandersnatch.config" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim | default (include "bandersnatch.pvc" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
