apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bandersnatch.job" . }}
  labels:
    {{- include "bandersnatch.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "bandersnatch.job" . }}
      labels:
        {{- include "bandersnatch.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-job
          image: "alpine:latest"
          command:
            - "/bin/cp"
          args:
            - "/opt/bandersnatch.conf.initial"
            - "/conf/bandersnatch.conf"
          volumeMounts:
            - name: initial-config
              mountPath: /opt
            - name: config
              mountPath: /conf
      volumes:
        - name: initial-config
          configMap:
            name: {{ template "bandersnatch.config" . }}
        - name: config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim | default (include "bandersnatch.config" .) }}
          {{- end }}
