apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "wormhole.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service_nginx.type }}
  ports:
    - port: {{ .Values.service_nginx.port }}
      targetPort: http-nginx
      protocol: TCP
      name: http-nginx
  selector:
    {{- include "wormhole.selectorLabels" . | nindent 4 }}
